entity-name-format: "ยง5%s ยงb(%s)" # Zombie (4x)
spawner-name-format: "%s (%sX) Spawner" # Zombie (4x) Spawner
level-up-particle:
  enable: true
  particle: "VILLAGER_HAPPY"
max-entity-stack: 100
max-spawner-stack: 100