entity-name-format: "&5%s &b(%sX)" # Zombie (4X)
spawner-name-format: "%s (%sX) Spawner" # Zombie (4X) Spawner
inventory-name-format: "%s Spawner (%sX)" # Zombie Spawner (4X)
level-up-particle:
  enable: true
  particle: "VILLAGER_HAPPY"
max-entity-stack: 100
max-spawner-stack: 100
natural-spawner-remover:
  enable: true
  worlds:
    - world